version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "80:80"
    container_name: react-devops-app
    restart: unless-stopped
    # Health check to ensure container is running properly
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
